workflows:
  flutter-android-release:
    name: Flutter Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-signing
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Clean and Fetch Packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Build Android APK via Pure Gradle
        script: |
          cd android
          # Memberikan izin akses eksekusi (CHMOD) pada file gradlew agar tidak Permission Denied
          chmod +x gradlew
          # Jalankan build murni
          ./gradlew assembleRelease --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
