workflows:
  flutter-android-release:
    name: Flutter Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - android-signing
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: Clean and Fetch Packages
        script: |
          flutter clean
          flutter packages pub get
      - name: Inject Missing Gradle Jar Automatically
        script: |
          cd android
          mkdir -p gradle/wrapper
          curl -Lo gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/v7.6.3/gradle/wrapper/gradle-wrapper.jar
          chmod +x gradlew
      - name: Build Android APK via Pure Gradle
        script: |
          cd android
          # -x :gradle:compileKotlin digunakan untuk mematikan paksa tugas yang bikin eror dari kemarin
          ./gradlew :app:assembleRelease \
            -x :gradle:compileKotlin \
            -Dorg.gradle.java.home=$JAVA_HOME \
            --no-daemon
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
