name: Build Flutter Android APK

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Prepare Build
        run: |
          # Hapus file yang sering bikin konflik
          rm -f .flutter-plugins .flutter-plugins-dependencies
          
          # Buat local.properties (PENTING)
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
          
          # Bersihkan project dengan Flutter CLI, bukan gradlew
          flutter clean
          flutter pub get

      - name: Build APK Release
        run: |
          # Langsung hajar build pakai flutter CLI
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: selz-monitor-apk
          path: build/app/outputs/flutter-apk/app-release.apk
